### ISSUE TITLE
if program exits abnormally it will fill up the DMA

### ISSUE THREAD

**Issue by LickTheCheese** [markondej/fm_transmitter#107]
if you kill the fm transmitter while its running enough times, it will nolonger be able to broadcast anything, exiting with the error `Error: Cannot allocate memory`

**Comment by markondej** [comment]
It is related with DMA memory allocation. Since it is managed by Videocore the allocated memory must be released upon program termination, in other case linux kernel won't release it by itself.
Try closing program grefully (kill -2) instead of killing it using KILL signal

**Comment by LickTheCheese** [comment]
ah thanks `kill -2` works
