### ISSUE TITLE
how to read "fifo" file?

### ISSUE THREAD

**Issue by SJ50** [markondej/fm_transmitter#11]
with shairport I am piping airplay out put to fifo file named "airpipe"
`sudo shairport-sync -v -a testp -o pipe -- ~/airpipe`
than I am starting fm_transmitter with
`sudo ~/fm_transmitter_original/fm_transmitter ~/airpipe 103`
and I am getting this error
`Error: Error while opening /home/pi/airpipe, WAVE file expected`

**Comment by markondej** [comment]
Named pipes are not supported yet, but reported in issue #8. Work is in progress....

**Comment by frriction** [comment]
Ok 
Thank you for clarifying.
