### ISSUE TITLE
An error occurred while executing the -r command

### ISSUE THREAD

**Issue by ghost** [markondej/fm_transmitter#119]
I received an error `Error: Cannot open 100, file does not exist`  when executing the command `sudo ./fm_transmitter -f 102.0 -r 100 hello.wav` 
Or when executing the command `sudo ./fm_transmitter -f 102.0 hello.wav -r 100` I get the error after hello.wav ends `Error: Cannot open 100, file does not exist`
Can someone help me? Sorry for my English not good!

**Comment by Blattoid** [comment]
-r does not accept an argument, it can only loop forever. So it thinks 100 is a file you want to play.
