### ISSUE TITLE
Error while running "Make" command

### ISSUE THREAD

**Issue by Sabering1** [markondej/fm_transmitter#121]
Hi i was just downloading this and while i was running a "make" command i got a error like this:
![Screenshot_20200914_181410_org connectbot](https://user-images.githubusercontent.com/39810634/93110927-f2084b80-f683-11ea-83ce-46cf08a95f44.jpg)
![Screenshot_20200914_181420_org connectbot](https://user-images.githubusercontent.com/39810634/93110952-f92f5980-f683-11ea-8075-1d89253ffc50.jpg)

**Comment by markondej** [comment]
Looks like broadcom library is missing or badly linked. Please specify your OS (Kali Linux, am I right?) and gcc version.

**Comment by Sabering1** [comment]
I am using Kali Linux 2020.3 on my RP zero w and the gcc version is (Debian 9.2.1-25) 9.2.1 20200123
Here is the screenshot:
![Screenshot_20200915_163905_org connectbot](https://user-images.githubusercontent.com/39810634/93228241-47eff880-f743-11ea-94bb-4de375edd658.jpg)

**Comment by Bl00dyDevil** [comment]
I have the same problem. I'm running Kali linux 2020.4 on RPi4. here is the log: 

```
g++ -Wall -O3 -std=c++11 -DVERSION=\"0.9.4\" -DEXECUTABLE=\"fm_transmitter\" -c main.cpp
g++ -Wall -O3 -std=c++11 -c mailbox.c
g++ -Wall -O3 -std=c++11 -c sample.cpp
g++ -Wall -O3 -std=c++11 -c wave_reader.cpp
g++ -Wall -O3 -std=c++11 -fno-strict-aliasing -I/opt/vc/include -c transmitter.cpp
transmitter.cpp:36:10: fatal error: bcm_host.h: No such file or directory
   36 | #include <bcm_host.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [makefile:22: transmitter.o] Error 1
```
Btw yes i have root permissions.

**Comment by markondej** [comment]
I've updated the readme, please try installing Broadcom packages first: libraspberrypi-dev  libraspberrypi-bin
