### ISSUE TITLE
How to add RDS info

### ISSUE THREAD

**Issue by Anonym2000TM** [markondej/fm_transmitter#131]
Hey there,
i runned this project on my RPi 3B and it works perfectly, but is there any way to broadcast some info with it?
I mean name of station (ex.: _WLTW-FM_) and some description (ex.: _now playing - Beatles, Yesterday_)
Thank you for any replies

**Comment by rsaxvc** [comment]
I don't think this project supports RDS encoding, but https://github.com/ChristopheJacquet/PiFmRds does.
