### ISSUE TITLE
[NOT AN ISSUE, QUESTION] Is it possible to do a true random/shuffle with all music?

### ISSUE THREAD

**Issue by Markieyer** [markondej/fm_transmitter#136]
I'd like to be able to shuffle through my music so I get different songs on the station each time, the best I can do is a wildcard/*, but that goes alphabetically, so it's not random at all, and I'm not sure how I could make it truly random, is that even a thing you can do with Linux? Thanks in advance

**Comment by markondej** [comment]
like @superamario64 suggested in #122 one may try writing script copying music to temporary folder in random order

**Comment by philippludwig** [comment]
You could use a combination of `find` and `sort --random`.
