### ISSUE TITLE
I can't receive it from the radio.

### ISSUE THREAD

**Issue by jay9455** [markondej/fm_transmitter#147]
Even though I followed all the guidelines on github, it is not playing normally.

I connected the cable like the picture below to GPIO4 or GPIO21, but when I set the frequency on the radio, only noise is heard.

Is there any way to solve it?

![cable](https://user-images.githubusercontent.com/83913698/133446248-0f4cf11f-0392-492c-ac39-98751ed457e6.jpg)

**Comment by gitiliya** [comment]
Im still tinkering around with mine but if you use -b to make it louder you can actually begin to hear it, sudo ./fm_transmitter -f 87.60 -b 3000 rager.wav

**Comment by KodeNoleg** [comment]
What are you putting in the terminal to play the music?

**Comment by jay9455** [comment]
> 음악을 재생하기 위해 터미널에 무엇을 넣습니까?

`sudo ./fm_transmitter -f 102.0 acoustic_guitar_duet.wav`

I used the command above.

However, when Ubuntu was reinstalled, it worked normally.
