### ISSUE TITLE
FRS two-way-radios?

### ISSUE THREAD

**Issue by ulisesvina** [markondej/fm_transmitter#159]
I'm trying to transmit (NOT RECEIVE) audio with my Raspberry Pi using this program to a FRS two-way-radio (Midland LXT114) on it's channel 1 (462.562MHz freq, 12.5KHz bandwidth), when I approach the radio to the Raspberry Pi's antenna, it does pick up something, but it's just noice. I can't seem to play anything at all through it, even the example `acoustic_guitar_duet.wav` file has the same result.

**Comment by markondej** [comment]
462 MHz with 12.5 KHz bandwidth is way too high frequency for RPi's clock hardware, it simply does not have sufficient resolution to transmit analog sound on such high frequency.

**Comment by ulisesvina** [comment]
Should have closed this issue before, but thanks. Anyways, I managed to make it work (yes, even being such high frequency). My problem was that those kind of radios does not use FM, but NBFM (narrow-band FM). But thanks a lot anyway.
