### ISSUE TITLE
Stream  music from PC to Raspberry Pi

### ISSUE THREAD

**Issue by VariousGames** [markondej/fm_transmitter#162]
Is there a way to play Stream files?
I like to stream music from my PC to an Raspberry Pi  with this script

**Comment by markondej** [comment]
Do you mean streaming files from PC to Raspberry Pi in order to trasmit them?

**Comment by VariousGames** [comment]
Yeah, or via an Stream file like stream.pls

**Comment by AstaFatherSatan** [comment]
I did this with cvlc and pulse audio before.

**Comment by AstaFatherSatan** [comment]
Can we close the issue now i resolved it?

**Comment by AstaFatherSatan** [comment]
Thank you

**Comment by AstaFatherSatan** [comment]
Did some corrections.
