### ISSUE TITLE
Bus Error when using -d 255

### ISSUE THREAD

**Issue by lodmc7** [markondej/fm_transmitter#164]
I enter this command on my terminal 

```bash
$ sudo ./fm_transmitter -f 88.0 -d 255 acoustic_guitar_duet.wav
```

```
Broadcasting at 102 MHz with 200 kHz bandwidth
Playing: acoustic_guitar_duet.wav, 22050 Hz, 16 bits, mono
Bus error
```

How do I fix this? Thank you!

**Comment by Friuuu** [comment]
I had the same issue. I have raspberry pi 3b+. I realized that i had the 64 bit version of raspbian so i tried to switch to the 32 bit version and it fixed this. It is worth trying out at least.

**Comment by markondej** [comment]
Thanks for your feedback I will check if this software runs on arm64 platform

**Comment by markondej** [comment]
Fixed
