### ISSUE TITLE
Radio Data System not working

### ISSUE THREAD

**Issue by Cheerstoast** [markondej/fm_transmitter#177]
This is more of a suggestion than an issue, but Radio Data System is not supported, and it would be very nice if you could add the functionality.

If unfamiliar with Radio Data System, it's basically the system that transmits the station name, song genre, description, etc. to the radio receivers.
See wiki:
https://en.wikipedia.org/wiki/Radio_Data_System

I understand this feature might be hard.
Thanks anyway! You deserve another star.

**Comment by wodowiesel** [comment]
@Cheerstoast There is actually a version with RDS and other forks: https://github.com/ChristopheJacquet/PiFmRds ;)

**Comment by Cheerstoast** [comment]
Hmm. Looks like other people accomplished this!
Developer's enthusiasm never stops, eh?

Anyway, @markondej , keep in mind that RDS would be a valuable feature to add to this project!
