### ISSUE TITLE
output to audio jack

### ISSUE THREAD

**Issue by WhatWouldJoeDo** [markondej/fm_transmitter#178]
Hi, i want the output of the frequency modulated signal to be the audio jack of the rpi and not GPIO4.
Is there a way of doing this?

**Comment by markondej** [comment]
Since there is a bandpass filters on both JACK socket's audio channels I don't think this is going to work

**Comment by WhatWouldJoeDo** [comment]
@markondej thanks for your answer. Your absolutely right i forgot about the filter 🥲
