### ISSUE TITLE
Is there a way to redirect all audio to the FM transmitter?

### ISSUE THREAD

**Issue by tarasius** [markondej/fm_transmitter#18]
Good day.
I want to output all audio played on my system to the FM transmitter. I.e. from mediaplayer, games, etc. Is it possible?
If no, maybe there is a special solution for the Kodi mediaserver?
Thanks.

**Comment by markondej** [comment]
Don't know, I'd try redirecting ALSA output to stdin and then it could be transmitted as normal stream.

See: https://carthick.wordpress.com/2007/11/26/linux-recording-soundcard-output-using-arecord/

**Comment by reukiodo** [comment]
The next step could be to create a service that while running exposes the fm transmitter as a sound sink (speaker) that the user can then configure as an output for all system sounds.
