### ISSUE TITLE
Am I missing something??

### ISSUE THREAD

**Issue by jaxtheop** [markondej/fm_transmitter#27]
Hey all,

heres what happens when i try to use this, it always gives me an error that says that it does not recognize the command "sudo: ./fm_transmitter: command not found" and that would be because there is no file called fm_transmitter to download from this github, so where is it?? or am i missing something??

**Comment by colasama** [comment]
`git clone https://github.com/markondej/fm_transmitter`
`cd fm_transmitter`
`make`
:-)

**Comment by jaxtheop** [comment]
Thank you so much!!!  and sorry for my stupidity, this is my first raspberry pi project

**Comment by xxiegodayxx** [comment]
I need this mans, that didn't work for me
