### ISSUE TITLE
Transmit by stdio stream

### ISSUE THREAD

**Issue by SandPox** [markondej/fm_transmitter#3]
How about read from stdio stream instead of file? by do that I can transmit internet radio...

**Comment by markondej** [comment]
I'm working on it currently in new branch. Adding this feature is matter of few days.

**Comment by markondej** [comment]
I just made an initial commit of version that supports stdin data streaming. It's in threads branch. 8kHz mono 8 bit streams are supported, but you can modify those options in stdin_reader.h file.

**Comment by markondej** [comment]
Done
