### ISSUE TITLE
Can not change the frequency

### ISSUE THREAD

**Issue by Tunguska12** [markondej/fm_transmitter#42]
Hi guys! 
Currently, I can not change the broadcast frequency.
First, I used command  `sudo ./fm_transmitter [-f 100] [-r] filename ` to play a song in 100Mhz then I ctrl+C to stop it.
I used another command `sudo ./fm_transmitter [-f 85.5] [-r] filename` to play the song in different frequency but it did not change. The song still stayed in old frequency 100Mhz.

What I am supposed to do guys? I'm just a newbie in Linux as well as Raspberry. Any suggestion would be appriciated.

**Comment by markondej** [comment]
Hi,
just don't write square brackets (they mean something optional)

**Comment by Tunguska12** [comment]
Yeah it worked! thanks a lot :D
and I want to ask just one more question, what I have to do if I want to play all songs in a folder inside /fm_transmitter.

**Comment by markondej** [comment]
You can add multiple files and even loop them, please see issue: #56
