### ISSUE TITLE
Does USB sound card Line Out work for transmitting

### ISSUE THREAD

**Issue by tycrek** [markondej/fm_transmitter#54]
The readme wasnt entirely clear on USB sound card. Can you use the line out of a USB sound card to transmit instead of a gpio? I do not want to record from a microphone, rather i want to play a sound file. Is this possible?? Thanks.

**Comment by clerie** [comment]
I'am not sure what you mean.
You can't transmit radio signals using the sound card (with this software).
The sound card is only used for AUX input, so you can connect your phone etc. and transmit the sound output of these devices.
