### ISSUE TITLE
Loop and playing playlists 

### ISSUE THREAD

**Issue by ironbat24** [markondej/fm_transmitter#56]
Hello,I'm very new to this so idk how to put this in words properly but is there a way to tell the program to play 2-3 songs on loop without any additional code?

**Comment by snakeeater4526** [comment]
hello i also want to play playlist
it is possible?? and how??
thank

**Comment by markondej** [comment]
It is possible now, simply pass different file names at end of command, eg:
```
sudo ./fm_transmitter -f 103.0 file1.wav file2.wav
```
You can loop them, with -r param also
