### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by meaz** [markondej/fm_transmitter#6]
Hi,

I'm a complete Noob! However, I'm really interested in the fm_transmitter as I just got a raspberry pie 2 and would love to try a radio with my pupils. You wrote that to compile this project I can use Code::Blocks IDE (http://codeblocks.org/)... But I don't know how to do so... I downloaded Code Block... And then? What do I need to do?

Thanks a lot.

**Comment by SandPox** [comment]
open codeblock, open project, build->build

**Comment by meaz** [comment]
Thanks! I opened "fm_transmitter.cbp"; clicked on build then build, but I have an error.

`
||=== Build: Debug in fm_transmitter (compiler: GNU GCC Compiler) ===|`
`C:\Users\Meaz\Desktop\fm_transmitter-master\fm_transmitter-master\stdin_reader.h|54|error: 'pthread_t' does not name a type|`
`||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|`

Did I do something wrong?

Thx

**Comment by markondej** [comment]
You are trying to compile it on your Windows computer. As codeblocks works both on windows and linux based OS, fm_transmitter can be compiled only under unix (linux).

You can make compilation right on your RPi device, using raspbian system:
1. Connect your RPi to internet via wifi dongle or via ethernet port
2. Type "sudo apt-get update" in console
3. Type "sudo apt-get install codeblocks codeblocks-contrib" in console, confirm action by typing "Y"
4. Switch to graphical user interface mode (i.e. byt typing "startx") in console
5. In menu (right upper corner of screen) select programming->codeblocks
6. Wait until codeblocks will be ready (takes some time on RPi 1), then open fm_transmitter.cbp and use build->build.
7. Your ready to use binary should be in fm_transmitter/bin/Debug location

**Comment by meaz** [comment]
It worked like a charm! Thanks a lot! I can't wait to try with my pupils!

**Comment by markondej** [comment]
sudo ./fm_transmitter [filename] [frequency] works only with plain-encoded WAVE files. In order to play mp3 etc. please use stdin streaming (like in second example, with use sox) ;)

**Comment by codeskyblue** [comment]
How about add a Makefile. I don't have a codeblocks  installed(too hard for me)

**Comment by markondej** [comment]
Looks like I won't escape from makefiles. I've added your makefile
