### ISSUE TITLE
Just play 5 seconds or less

### ISSUE THREAD

**Issue by MonsterDeveloper** [markondej/fm_transmitter#65]
On my RPi 3 when i send the command `sudo ./fm_transmitter -f 104.2 -r star_wars.wav` and only play for 4 or 5 seconds and goes off. what is happening?

**Comment by playinmyblues** [comment]
This seems to be a common issue. I found a solution online somewhere that detailed a short script to turn off the temperature monitoring on the CPU.


________________________________

**Comment by markondej** [comment]
Hi, please specify which RPi board and what kind of OS are you using.

**Comment by MonsterDeveloper** [comment]
So, my board is RPi 3 model B and my OS is Raspbian 8.0 Jessie

**Comment by MonsterDeveloper** [comment]
@markondej and I am using just jumper cables as my antenna. Like this:
![12 02 18 19 43](https://user-images.githubusercontent.com/16190582/36108138-23576256-102d-11e8-8dc4-a8b596577f70.jpg)

**Comment by MonsterDeveloper** [comment]
If @markondej you need demo, I can send you audio file of video.

**Comment by MonsterDeveloper** [comment]
Hmm, interesting thing that I booted into Kali Linux on my RPi, installed make, gcc and g++ and everything worked just fine. It seems that problem with os (Raspbian). WHat do you think it is?

**Comment by TheMakaf** [comment]
Was same problem. I used 800 mA power source, thats too low for radio transmitter work. Now I'm using 1.5 A or 2 A power source, everything works.

**Comment by playinmyblues** [comment]
The link to solve my problem is here:
https://raspberrypi.stackexchange.com/questions/47893/pifm-rds-cuts-off-after-a-few-seconds

In short, the command is:
sudo rmmod w1-gpio

I notice that somebody else had a problem that was solved using a better power source. I am using an RPi3 with an RPi power source rated for 5V 2.5A.

Given all that, I do not know why it works when I run the command provided above so it is best if you research the problem before using it.
