### ISSUE TITLE
fm_transmitter doens't exit after finish playback

### ISSUE THREAD

**Issue by mchilli** [markondej/fm_transmitter#67]
Hi there,
can anyone help me? i use this command:
`avconv -i "/path/to/file.mp3" -f wav -flags bitexact -ar 22.05k -ac 1 - | sudo ./fm_transmitter -f 98.5 -`
and to stream a file via stdin to fm_transmitter, works absolutly fine. But if the soundfile has ended, the program doens't exit. Maybe there isn't an EOF when streaming over stdin and the program will loop forever.
But how i can solve this?

**Comment by tetsaicn** [comment]
same problem (

**Comment by markondej** [comment]
will fix this soon
