### ISSUE TITLE
sudo ./fm_transmitter command not found

### ISSUE THREAD

**Issue by xxiegodayxx** [markondej/fm_transmitter#68]
So this is my very first project and I installed everything on the pi but when I try to use sudo ./fm_transmitter -f 106.2 star_wars.wav it says that the fm transmitter command was not found. I dont know how to fix this, I hope someone can answer this.

**Comment by xxiegodayxx** [comment]
Hello??

**Comment by markondej** [comment]
You need to clone this repository first (download source code), eg.:
`sudo git clone https://github.com/markondej/fm_transmitter`
then switch dictonary and compile source code:
`cd fm_transmitter
make`

**Comment by xxiegodayxx** [comment]
Alright, I did it and it's working now. Thank you so much!
