### ISSUE TITLE
nmap error

### ISSUE THREAD

**Issue by LonelyLuni** [markondej/fm_transmitter#89]

**Comment by markondej** [comment]
Please specify your system and GCC version, type:
```
uname -m
g++ --version
```
Error is thrown on external library, brought by Broadcom, I beleive its because you are compiling on aarch64 architecture. You can try to fix this, by adding -fpermissive to makefile on line 3, eg.
```
FLAGS = -Wall -O3 -std=c++11 -fpermissive
```
