### ISSUE TITLE
Does not stop transmitting after shutting down

### ISSUE THREAD

**Issue by jk0** [markondej/fm_transmitter#9]
I've seen this reported in other RPI FM transmitter variants also, where after shutting down the process using Ctrl+C, the process shuts down but the (blank/silent) transmissions continue until you either reboot the RPI, or run the following python script:

```
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(7, 0)
GPIO.cleanup()
```

Thankfully (in some sort of weird way) the spurious harmonics produced by not having a LPF alerted me when they started keying up my cross-band repeater. Otherwise these transmissions would have continued on. I also verified this behavior while watching the spectrum on the RTLSDR.

**Comment by markondej** [comment]
There are some options to fix this, but most basic is to switch GPIO port 4, which is our anthena output, back to IO operation mode (as I assume your python code does exactly the same). I'll add it in free moment.
